### ISSUE TITLE
This engine is too good

### ISSUE THREAD

**Issue by Bernatmago** [baransrc/Strawhat_Engine#2]
![image](https://user-images.githubusercontent.com/28431584/145215182-1d2f2078-4114-4ad4-909f-22c9cb9a3c50.png)

**Comment by baransrc** [comment]
Dear @Bernatmago, your issue seems unfixable, therefore wontfix.
![image](https://user-images.githubusercontent.com/42971567/145220306-e9823c37-1cb3-498b-9216-269af78c3000.png)
